-- 创建邮箱表
CREATE TABLE IF NOT EXISTS EPCC_EMAIL_CTRL (
    EEC_EMAIL VARCHAR(255) PRIMARY KEY,
    EEC_USERNAME VARCHAR(255) NOT NULL,
    EEC_DESC TEXT,
    EEC_CREATETIME DATETIME NOT NULL,
    EEC_MODTELLER VARCHAR(100),
    EEC_LASTMODTIME DATETIME
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_email ON EPCC_EMAIL_CTRL(EEC_EMAIL);
CREATE INDEX IF NOT EXISTS username_idx ON EPCC_EMAIL_CTRL(EEC_USERNAME);